from typing import List

class PyTitanTransformer:
    def __init__(self, vocab_size: int, dim: int, num_layers: int) -> None: ...
    def init_optimizer(self, lr: float) -> None: ...
    def save_weights(self, path: str) -> None: ...
    def load_weights(self, path: str) -> None: ...
    def reset_state(self) -> None: ...
    def forward(self, x_ids: List[int]) -> List[float]: ...
    def train_step(self, x_ids: List[int], target_ids: List[int]) -> float: ...

class PyTokenizer:
    def __init__(self, json_path: str) -> None: ...
    def encode(self, text: str) -> List[int]: ...
    def decode(self, ids: List[int]) -> str: ...
